// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Services/ClientService.proto

#include "Services/ClientService.pb.h"
#include "Services/ClientService.grpc.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/sync_stream.h>
#include <gmock/gmock.h>
namespace GrpcProject {
namespace Protos {
namespace Services {

class MockClientServiceStub : public ClientService::StubInterface {
 public:
  MOCK_METHOD3(CreateClient, ::grpc::Status(::grpc::ClientContext* context, const ::GrpcProject::Protos::Models::Client& request, ::GrpcProject::Protos::Helpers::ServiceStatus* response));
  MOCK_METHOD3(AsyncCreateClientRaw, ::grpc::ClientAsyncResponseReaderInterface< ::GrpcProject::Protos::Helpers::ServiceStatus>*(::grpc::ClientContext* context, const ::GrpcProject::Protos::Models::Client& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PrepareAsyncCreateClientRaw, ::grpc::ClientAsyncResponseReaderInterface< ::GrpcProject::Protos::Helpers::ServiceStatus>*(::grpc::ClientContext* context, const ::GrpcProject::Protos::Models::Client& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(ListClient, ::grpc::Status(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::GrpcProject::Protos::Models::ListClientResponse* response));
  MOCK_METHOD3(AsyncListClientRaw, ::grpc::ClientAsyncResponseReaderInterface< ::GrpcProject::Protos::Models::ListClientResponse>*(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PrepareAsyncListClientRaw, ::grpc::ClientAsyncResponseReaderInterface< ::GrpcProject::Protos::Models::ListClientResponse>*(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(InvoiceClient, ::grpc::Status(::grpc::ClientContext* context, const ::GrpcProject::Protos::Models::ClientId& request, ::GrpcProject::Protos::Models::Invoice* response));
  MOCK_METHOD3(AsyncInvoiceClientRaw, ::grpc::ClientAsyncResponseReaderInterface< ::GrpcProject::Protos::Models::Invoice>*(::grpc::ClientContext* context, const ::GrpcProject::Protos::Models::ClientId& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PrepareAsyncInvoiceClientRaw, ::grpc::ClientAsyncResponseReaderInterface< ::GrpcProject::Protos::Models::Invoice>*(::grpc::ClientContext* context, const ::GrpcProject::Protos::Models::ClientId& request, ::grpc::CompletionQueue* cq));
};

} // namespace GrpcProject
} // namespace Protos
} // namespace Services

