// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Services/InvoiceService.proto

#include "Services/InvoiceService.pb.h"
#include "Services/InvoiceService.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace GrpcProject {
namespace Protos {
namespace Services {

static const char* InvoiceService_method_names[] = {
  "/GrpcProject.Protos.Services.InvoiceService/RegsterInvoice",
  "/GrpcProject.Protos.Services.InvoiceService/GetInvoiceDetails",
  "/GrpcProject.Protos.Services.InvoiceService/ListInvoice",
};

std::unique_ptr< InvoiceService::Stub> InvoiceService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< InvoiceService::Stub> stub(new InvoiceService::Stub(channel, options));
  return stub;
}

InvoiceService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_RegsterInvoice_(InvoiceService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetInvoiceDetails_(InvoiceService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListInvoice_(InvoiceService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status InvoiceService::Stub::RegsterInvoice(::grpc::ClientContext* context, const ::GrpcProject::Protos::Models::Invoice& request, ::GrpcProject::Protos::Helpers::ServiceStatus* response) {
  return ::grpc::internal::BlockingUnaryCall< ::GrpcProject::Protos::Models::Invoice, ::GrpcProject::Protos::Helpers::ServiceStatus, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RegsterInvoice_, context, request, response);
}

void InvoiceService::Stub::async::RegsterInvoice(::grpc::ClientContext* context, const ::GrpcProject::Protos::Models::Invoice* request, ::GrpcProject::Protos::Helpers::ServiceStatus* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::GrpcProject::Protos::Models::Invoice, ::GrpcProject::Protos::Helpers::ServiceStatus, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegsterInvoice_, context, request, response, std::move(f));
}

void InvoiceService::Stub::async::RegsterInvoice(::grpc::ClientContext* context, const ::GrpcProject::Protos::Models::Invoice* request, ::GrpcProject::Protos::Helpers::ServiceStatus* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegsterInvoice_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::GrpcProject::Protos::Helpers::ServiceStatus>* InvoiceService::Stub::PrepareAsyncRegsterInvoiceRaw(::grpc::ClientContext* context, const ::GrpcProject::Protos::Models::Invoice& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::GrpcProject::Protos::Helpers::ServiceStatus, ::GrpcProject::Protos::Models::Invoice, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RegsterInvoice_, context, request);
}

::grpc::ClientAsyncResponseReader< ::GrpcProject::Protos::Helpers::ServiceStatus>* InvoiceService::Stub::AsyncRegsterInvoiceRaw(::grpc::ClientContext* context, const ::GrpcProject::Protos::Models::Invoice& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRegsterInvoiceRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status InvoiceService::Stub::GetInvoiceDetails(::grpc::ClientContext* context, const ::GrpcProject::Protos::Models::InvoiceId& request, ::GrpcProject::Protos::Models::Invoice* response) {
  return ::grpc::internal::BlockingUnaryCall< ::GrpcProject::Protos::Models::InvoiceId, ::GrpcProject::Protos::Models::Invoice, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetInvoiceDetails_, context, request, response);
}

void InvoiceService::Stub::async::GetInvoiceDetails(::grpc::ClientContext* context, const ::GrpcProject::Protos::Models::InvoiceId* request, ::GrpcProject::Protos::Models::Invoice* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::GrpcProject::Protos::Models::InvoiceId, ::GrpcProject::Protos::Models::Invoice, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetInvoiceDetails_, context, request, response, std::move(f));
}

void InvoiceService::Stub::async::GetInvoiceDetails(::grpc::ClientContext* context, const ::GrpcProject::Protos::Models::InvoiceId* request, ::GrpcProject::Protos::Models::Invoice* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetInvoiceDetails_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::GrpcProject::Protos::Models::Invoice>* InvoiceService::Stub::PrepareAsyncGetInvoiceDetailsRaw(::grpc::ClientContext* context, const ::GrpcProject::Protos::Models::InvoiceId& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::GrpcProject::Protos::Models::Invoice, ::GrpcProject::Protos::Models::InvoiceId, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetInvoiceDetails_, context, request);
}

::grpc::ClientAsyncResponseReader< ::GrpcProject::Protos::Models::Invoice>* InvoiceService::Stub::AsyncGetInvoiceDetailsRaw(::grpc::ClientContext* context, const ::GrpcProject::Protos::Models::InvoiceId& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetInvoiceDetailsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status InvoiceService::Stub::ListInvoice(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::GrpcProject::Protos::Models::ListInvoiceResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::google::protobuf::Empty, ::GrpcProject::Protos::Models::ListInvoiceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListInvoice_, context, request, response);
}

void InvoiceService::Stub::async::ListInvoice(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::GrpcProject::Protos::Models::ListInvoiceResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::google::protobuf::Empty, ::GrpcProject::Protos::Models::ListInvoiceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListInvoice_, context, request, response, std::move(f));
}

void InvoiceService::Stub::async::ListInvoice(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::GrpcProject::Protos::Models::ListInvoiceResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListInvoice_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::GrpcProject::Protos::Models::ListInvoiceResponse>* InvoiceService::Stub::PrepareAsyncListInvoiceRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::GrpcProject::Protos::Models::ListInvoiceResponse, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListInvoice_, context, request);
}

::grpc::ClientAsyncResponseReader< ::GrpcProject::Protos::Models::ListInvoiceResponse>* InvoiceService::Stub::AsyncListInvoiceRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListInvoiceRaw(context, request, cq);
  result->StartCall();
  return result;
}

InvoiceService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      InvoiceService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< InvoiceService::Service, ::GrpcProject::Protos::Models::Invoice, ::GrpcProject::Protos::Helpers::ServiceStatus, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](InvoiceService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::GrpcProject::Protos::Models::Invoice* req,
             ::GrpcProject::Protos::Helpers::ServiceStatus* resp) {
               return service->RegsterInvoice(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      InvoiceService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< InvoiceService::Service, ::GrpcProject::Protos::Models::InvoiceId, ::GrpcProject::Protos::Models::Invoice, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](InvoiceService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::GrpcProject::Protos::Models::InvoiceId* req,
             ::GrpcProject::Protos::Models::Invoice* resp) {
               return service->GetInvoiceDetails(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      InvoiceService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< InvoiceService::Service, ::google::protobuf::Empty, ::GrpcProject::Protos::Models::ListInvoiceResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](InvoiceService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::GrpcProject::Protos::Models::ListInvoiceResponse* resp) {
               return service->ListInvoice(ctx, req, resp);
             }, this)));
}

InvoiceService::Service::~Service() {
}

::grpc::Status InvoiceService::Service::RegsterInvoice(::grpc::ServerContext* context, const ::GrpcProject::Protos::Models::Invoice* request, ::GrpcProject::Protos::Helpers::ServiceStatus* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status InvoiceService::Service::GetInvoiceDetails(::grpc::ServerContext* context, const ::GrpcProject::Protos::Models::InvoiceId* request, ::GrpcProject::Protos::Models::Invoice* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status InvoiceService::Service::ListInvoice(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::GrpcProject::Protos::Models::ListInvoiceResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace GrpcProject
}  // namespace Protos
}  // namespace Services

