// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Services/InvoiceService.proto
#ifndef GRPC_Services_2fInvoiceService_2eproto__INCLUDED
#define GRPC_Services_2fInvoiceService_2eproto__INCLUDED

#include "Services/InvoiceService.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace GrpcProject {
namespace Protos {
namespace Services {

class InvoiceService final {
 public:
  static constexpr char const* service_full_name() {
    return "GrpcProject.Protos.Services.InvoiceService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status RegsterInvoice(::grpc::ClientContext* context, const ::GrpcProject::Protos::Models::Invoice& request, ::GrpcProject::Protos::Helpers::ServiceStatus* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GrpcProject::Protos::Helpers::ServiceStatus>> AsyncRegsterInvoice(::grpc::ClientContext* context, const ::GrpcProject::Protos::Models::Invoice& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GrpcProject::Protos::Helpers::ServiceStatus>>(AsyncRegsterInvoiceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GrpcProject::Protos::Helpers::ServiceStatus>> PrepareAsyncRegsterInvoice(::grpc::ClientContext* context, const ::GrpcProject::Protos::Models::Invoice& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GrpcProject::Protos::Helpers::ServiceStatus>>(PrepareAsyncRegsterInvoiceRaw(context, request, cq));
    }
    virtual ::grpc::Status GetInvoiceDetails(::grpc::ClientContext* context, const ::GrpcProject::Protos::Models::InvoiceId& request, ::GrpcProject::Protos::Models::Invoice* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GrpcProject::Protos::Models::Invoice>> AsyncGetInvoiceDetails(::grpc::ClientContext* context, const ::GrpcProject::Protos::Models::InvoiceId& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GrpcProject::Protos::Models::Invoice>>(AsyncGetInvoiceDetailsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GrpcProject::Protos::Models::Invoice>> PrepareAsyncGetInvoiceDetails(::grpc::ClientContext* context, const ::GrpcProject::Protos::Models::InvoiceId& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GrpcProject::Protos::Models::Invoice>>(PrepareAsyncGetInvoiceDetailsRaw(context, request, cq));
    }
    virtual ::grpc::Status ListInvoice(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::GrpcProject::Protos::Models::ListInvoiceResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GrpcProject::Protos::Models::ListInvoiceResponse>> AsyncListInvoice(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GrpcProject::Protos::Models::ListInvoiceResponse>>(AsyncListInvoiceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GrpcProject::Protos::Models::ListInvoiceResponse>> PrepareAsyncListInvoice(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::GrpcProject::Protos::Models::ListInvoiceResponse>>(PrepareAsyncListInvoiceRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void RegsterInvoice(::grpc::ClientContext* context, const ::GrpcProject::Protos::Models::Invoice* request, ::GrpcProject::Protos::Helpers::ServiceStatus* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RegsterInvoice(::grpc::ClientContext* context, const ::GrpcProject::Protos::Models::Invoice* request, ::GrpcProject::Protos::Helpers::ServiceStatus* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetInvoiceDetails(::grpc::ClientContext* context, const ::GrpcProject::Protos::Models::InvoiceId* request, ::GrpcProject::Protos::Models::Invoice* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetInvoiceDetails(::grpc::ClientContext* context, const ::GrpcProject::Protos::Models::InvoiceId* request, ::GrpcProject::Protos::Models::Invoice* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void ListInvoice(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::GrpcProject::Protos::Models::ListInvoiceResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ListInvoice(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::GrpcProject::Protos::Models::ListInvoiceResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::GrpcProject::Protos::Helpers::ServiceStatus>* AsyncRegsterInvoiceRaw(::grpc::ClientContext* context, const ::GrpcProject::Protos::Models::Invoice& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::GrpcProject::Protos::Helpers::ServiceStatus>* PrepareAsyncRegsterInvoiceRaw(::grpc::ClientContext* context, const ::GrpcProject::Protos::Models::Invoice& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::GrpcProject::Protos::Models::Invoice>* AsyncGetInvoiceDetailsRaw(::grpc::ClientContext* context, const ::GrpcProject::Protos::Models::InvoiceId& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::GrpcProject::Protos::Models::Invoice>* PrepareAsyncGetInvoiceDetailsRaw(::grpc::ClientContext* context, const ::GrpcProject::Protos::Models::InvoiceId& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::GrpcProject::Protos::Models::ListInvoiceResponse>* AsyncListInvoiceRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::GrpcProject::Protos::Models::ListInvoiceResponse>* PrepareAsyncListInvoiceRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status RegsterInvoice(::grpc::ClientContext* context, const ::GrpcProject::Protos::Models::Invoice& request, ::GrpcProject::Protos::Helpers::ServiceStatus* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GrpcProject::Protos::Helpers::ServiceStatus>> AsyncRegsterInvoice(::grpc::ClientContext* context, const ::GrpcProject::Protos::Models::Invoice& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GrpcProject::Protos::Helpers::ServiceStatus>>(AsyncRegsterInvoiceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GrpcProject::Protos::Helpers::ServiceStatus>> PrepareAsyncRegsterInvoice(::grpc::ClientContext* context, const ::GrpcProject::Protos::Models::Invoice& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GrpcProject::Protos::Helpers::ServiceStatus>>(PrepareAsyncRegsterInvoiceRaw(context, request, cq));
    }
    ::grpc::Status GetInvoiceDetails(::grpc::ClientContext* context, const ::GrpcProject::Protos::Models::InvoiceId& request, ::GrpcProject::Protos::Models::Invoice* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GrpcProject::Protos::Models::Invoice>> AsyncGetInvoiceDetails(::grpc::ClientContext* context, const ::GrpcProject::Protos::Models::InvoiceId& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GrpcProject::Protos::Models::Invoice>>(AsyncGetInvoiceDetailsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GrpcProject::Protos::Models::Invoice>> PrepareAsyncGetInvoiceDetails(::grpc::ClientContext* context, const ::GrpcProject::Protos::Models::InvoiceId& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GrpcProject::Protos::Models::Invoice>>(PrepareAsyncGetInvoiceDetailsRaw(context, request, cq));
    }
    ::grpc::Status ListInvoice(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::GrpcProject::Protos::Models::ListInvoiceResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GrpcProject::Protos::Models::ListInvoiceResponse>> AsyncListInvoice(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GrpcProject::Protos::Models::ListInvoiceResponse>>(AsyncListInvoiceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GrpcProject::Protos::Models::ListInvoiceResponse>> PrepareAsyncListInvoice(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::GrpcProject::Protos::Models::ListInvoiceResponse>>(PrepareAsyncListInvoiceRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void RegsterInvoice(::grpc::ClientContext* context, const ::GrpcProject::Protos::Models::Invoice* request, ::GrpcProject::Protos::Helpers::ServiceStatus* response, std::function<void(::grpc::Status)>) override;
      void RegsterInvoice(::grpc::ClientContext* context, const ::GrpcProject::Protos::Models::Invoice* request, ::GrpcProject::Protos::Helpers::ServiceStatus* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetInvoiceDetails(::grpc::ClientContext* context, const ::GrpcProject::Protos::Models::InvoiceId* request, ::GrpcProject::Protos::Models::Invoice* response, std::function<void(::grpc::Status)>) override;
      void GetInvoiceDetails(::grpc::ClientContext* context, const ::GrpcProject::Protos::Models::InvoiceId* request, ::GrpcProject::Protos::Models::Invoice* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ListInvoice(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::GrpcProject::Protos::Models::ListInvoiceResponse* response, std::function<void(::grpc::Status)>) override;
      void ListInvoice(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::GrpcProject::Protos::Models::ListInvoiceResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::GrpcProject::Protos::Helpers::ServiceStatus>* AsyncRegsterInvoiceRaw(::grpc::ClientContext* context, const ::GrpcProject::Protos::Models::Invoice& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::GrpcProject::Protos::Helpers::ServiceStatus>* PrepareAsyncRegsterInvoiceRaw(::grpc::ClientContext* context, const ::GrpcProject::Protos::Models::Invoice& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::GrpcProject::Protos::Models::Invoice>* AsyncGetInvoiceDetailsRaw(::grpc::ClientContext* context, const ::GrpcProject::Protos::Models::InvoiceId& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::GrpcProject::Protos::Models::Invoice>* PrepareAsyncGetInvoiceDetailsRaw(::grpc::ClientContext* context, const ::GrpcProject::Protos::Models::InvoiceId& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::GrpcProject::Protos::Models::ListInvoiceResponse>* AsyncListInvoiceRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::GrpcProject::Protos::Models::ListInvoiceResponse>* PrepareAsyncListInvoiceRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_RegsterInvoice_;
    const ::grpc::internal::RpcMethod rpcmethod_GetInvoiceDetails_;
    const ::grpc::internal::RpcMethod rpcmethod_ListInvoice_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status RegsterInvoice(::grpc::ServerContext* context, const ::GrpcProject::Protos::Models::Invoice* request, ::GrpcProject::Protos::Helpers::ServiceStatus* response);
    virtual ::grpc::Status GetInvoiceDetails(::grpc::ServerContext* context, const ::GrpcProject::Protos::Models::InvoiceId* request, ::GrpcProject::Protos::Models::Invoice* response);
    virtual ::grpc::Status ListInvoice(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::GrpcProject::Protos::Models::ListInvoiceResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_RegsterInvoice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RegsterInvoice() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_RegsterInvoice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegsterInvoice(::grpc::ServerContext* /*context*/, const ::GrpcProject::Protos::Models::Invoice* /*request*/, ::GrpcProject::Protos::Helpers::ServiceStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRegsterInvoice(::grpc::ServerContext* context, ::GrpcProject::Protos::Models::Invoice* request, ::grpc::ServerAsyncResponseWriter< ::GrpcProject::Protos::Helpers::ServiceStatus>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetInvoiceDetails : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetInvoiceDetails() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetInvoiceDetails() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetInvoiceDetails(::grpc::ServerContext* /*context*/, const ::GrpcProject::Protos::Models::InvoiceId* /*request*/, ::GrpcProject::Protos::Models::Invoice* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetInvoiceDetails(::grpc::ServerContext* context, ::GrpcProject::Protos::Models::InvoiceId* request, ::grpc::ServerAsyncResponseWriter< ::GrpcProject::Protos::Models::Invoice>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ListInvoice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ListInvoice() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_ListInvoice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListInvoice(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::GrpcProject::Protos::Models::ListInvoiceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListInvoice(::grpc::ServerContext* context, ::google::protobuf::Empty* request, ::grpc::ServerAsyncResponseWriter< ::GrpcProject::Protos::Models::ListInvoiceResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_RegsterInvoice<WithAsyncMethod_GetInvoiceDetails<WithAsyncMethod_ListInvoice<Service > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_RegsterInvoice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RegsterInvoice() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::GrpcProject::Protos::Models::Invoice, ::GrpcProject::Protos::Helpers::ServiceStatus>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::GrpcProject::Protos::Models::Invoice* request, ::GrpcProject::Protos::Helpers::ServiceStatus* response) { return this->RegsterInvoice(context, request, response); }));}
    void SetMessageAllocatorFor_RegsterInvoice(
        ::grpc::MessageAllocator< ::GrpcProject::Protos::Models::Invoice, ::GrpcProject::Protos::Helpers::ServiceStatus>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::GrpcProject::Protos::Models::Invoice, ::GrpcProject::Protos::Helpers::ServiceStatus>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RegsterInvoice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegsterInvoice(::grpc::ServerContext* /*context*/, const ::GrpcProject::Protos::Models::Invoice* /*request*/, ::GrpcProject::Protos::Helpers::ServiceStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RegsterInvoice(
      ::grpc::CallbackServerContext* /*context*/, const ::GrpcProject::Protos::Models::Invoice* /*request*/, ::GrpcProject::Protos::Helpers::ServiceStatus* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetInvoiceDetails : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetInvoiceDetails() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::GrpcProject::Protos::Models::InvoiceId, ::GrpcProject::Protos::Models::Invoice>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::GrpcProject::Protos::Models::InvoiceId* request, ::GrpcProject::Protos::Models::Invoice* response) { return this->GetInvoiceDetails(context, request, response); }));}
    void SetMessageAllocatorFor_GetInvoiceDetails(
        ::grpc::MessageAllocator< ::GrpcProject::Protos::Models::InvoiceId, ::GrpcProject::Protos::Models::Invoice>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::GrpcProject::Protos::Models::InvoiceId, ::GrpcProject::Protos::Models::Invoice>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetInvoiceDetails() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetInvoiceDetails(::grpc::ServerContext* /*context*/, const ::GrpcProject::Protos::Models::InvoiceId* /*request*/, ::GrpcProject::Protos::Models::Invoice* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetInvoiceDetails(
      ::grpc::CallbackServerContext* /*context*/, const ::GrpcProject::Protos::Models::InvoiceId* /*request*/, ::GrpcProject::Protos::Models::Invoice* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ListInvoice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ListInvoice() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::GrpcProject::Protos::Models::ListInvoiceResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::google::protobuf::Empty* request, ::GrpcProject::Protos::Models::ListInvoiceResponse* response) { return this->ListInvoice(context, request, response); }));}
    void SetMessageAllocatorFor_ListInvoice(
        ::grpc::MessageAllocator< ::google::protobuf::Empty, ::GrpcProject::Protos::Models::ListInvoiceResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::google::protobuf::Empty, ::GrpcProject::Protos::Models::ListInvoiceResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ListInvoice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListInvoice(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::GrpcProject::Protos::Models::ListInvoiceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListInvoice(
      ::grpc::CallbackServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::GrpcProject::Protos::Models::ListInvoiceResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_RegsterInvoice<WithCallbackMethod_GetInvoiceDetails<WithCallbackMethod_ListInvoice<Service > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_RegsterInvoice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RegsterInvoice() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_RegsterInvoice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegsterInvoice(::grpc::ServerContext* /*context*/, const ::GrpcProject::Protos::Models::Invoice* /*request*/, ::GrpcProject::Protos::Helpers::ServiceStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetInvoiceDetails : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetInvoiceDetails() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetInvoiceDetails() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetInvoiceDetails(::grpc::ServerContext* /*context*/, const ::GrpcProject::Protos::Models::InvoiceId* /*request*/, ::GrpcProject::Protos::Models::Invoice* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ListInvoice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ListInvoice() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_ListInvoice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListInvoice(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::GrpcProject::Protos::Models::ListInvoiceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_RegsterInvoice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RegsterInvoice() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_RegsterInvoice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegsterInvoice(::grpc::ServerContext* /*context*/, const ::GrpcProject::Protos::Models::Invoice* /*request*/, ::GrpcProject::Protos::Helpers::ServiceStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRegsterInvoice(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetInvoiceDetails : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetInvoiceDetails() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetInvoiceDetails() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetInvoiceDetails(::grpc::ServerContext* /*context*/, const ::GrpcProject::Protos::Models::InvoiceId* /*request*/, ::GrpcProject::Protos::Models::Invoice* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetInvoiceDetails(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ListInvoice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ListInvoice() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_ListInvoice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListInvoice(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::GrpcProject::Protos::Models::ListInvoiceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListInvoice(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RegsterInvoice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RegsterInvoice() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RegsterInvoice(context, request, response); }));
    }
    ~WithRawCallbackMethod_RegsterInvoice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RegsterInvoice(::grpc::ServerContext* /*context*/, const ::GrpcProject::Protos::Models::Invoice* /*request*/, ::GrpcProject::Protos::Helpers::ServiceStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RegsterInvoice(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetInvoiceDetails : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetInvoiceDetails() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetInvoiceDetails(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetInvoiceDetails() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetInvoiceDetails(::grpc::ServerContext* /*context*/, const ::GrpcProject::Protos::Models::InvoiceId* /*request*/, ::GrpcProject::Protos::Models::Invoice* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetInvoiceDetails(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ListInvoice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ListInvoice() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ListInvoice(context, request, response); }));
    }
    ~WithRawCallbackMethod_ListInvoice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListInvoice(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::GrpcProject::Protos::Models::ListInvoiceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListInvoice(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RegsterInvoice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RegsterInvoice() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::GrpcProject::Protos::Models::Invoice, ::GrpcProject::Protos::Helpers::ServiceStatus>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::GrpcProject::Protos::Models::Invoice, ::GrpcProject::Protos::Helpers::ServiceStatus>* streamer) {
                       return this->StreamedRegsterInvoice(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RegsterInvoice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RegsterInvoice(::grpc::ServerContext* /*context*/, const ::GrpcProject::Protos::Models::Invoice* /*request*/, ::GrpcProject::Protos::Helpers::ServiceStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRegsterInvoice(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::GrpcProject::Protos::Models::Invoice,::GrpcProject::Protos::Helpers::ServiceStatus>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetInvoiceDetails : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetInvoiceDetails() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::GrpcProject::Protos::Models::InvoiceId, ::GrpcProject::Protos::Models::Invoice>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::GrpcProject::Protos::Models::InvoiceId, ::GrpcProject::Protos::Models::Invoice>* streamer) {
                       return this->StreamedGetInvoiceDetails(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetInvoiceDetails() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetInvoiceDetails(::grpc::ServerContext* /*context*/, const ::GrpcProject::Protos::Models::InvoiceId* /*request*/, ::GrpcProject::Protos::Models::Invoice* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetInvoiceDetails(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::GrpcProject::Protos::Models::InvoiceId,::GrpcProject::Protos::Models::Invoice>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ListInvoice : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ListInvoice() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::google::protobuf::Empty, ::GrpcProject::Protos::Models::ListInvoiceResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::google::protobuf::Empty, ::GrpcProject::Protos::Models::ListInvoiceResponse>* streamer) {
                       return this->StreamedListInvoice(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ListInvoice() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ListInvoice(::grpc::ServerContext* /*context*/, const ::google::protobuf::Empty* /*request*/, ::GrpcProject::Protos::Models::ListInvoiceResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedListInvoice(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::google::protobuf::Empty,::GrpcProject::Protos::Models::ListInvoiceResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_RegsterInvoice<WithStreamedUnaryMethod_GetInvoiceDetails<WithStreamedUnaryMethod_ListInvoice<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_RegsterInvoice<WithStreamedUnaryMethod_GetInvoiceDetails<WithStreamedUnaryMethod_ListInvoice<Service > > > StreamedService;
};

}  // namespace Services
}  // namespace Protos
}  // namespace GrpcProject


#endif  // GRPC_Services_2fInvoiceService_2eproto__INCLUDED
