// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Services/ProductService.proto

#include "Services/ProductService.pb.h"
#include "Services/ProductService.grpc.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/sync_stream.h>
#include <gmock/gmock.h>
namespace GrpcProject {
namespace Protos {
namespace Services {

class MockProductServiceStub : public ProductService::StubInterface {
 public:
  MOCK_METHOD3(CreateProduct, ::grpc::Status(::grpc::ClientContext* context, const ::GrpcProject::Protos::Models::Product& request, ::GrpcProject::Protos::Helpers::ServiceStatus* response));
  MOCK_METHOD3(AsyncCreateProductRaw, ::grpc::ClientAsyncResponseReaderInterface< ::GrpcProject::Protos::Helpers::ServiceStatus>*(::grpc::ClientContext* context, const ::GrpcProject::Protos::Models::Product& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PrepareAsyncCreateProductRaw, ::grpc::ClientAsyncResponseReaderInterface< ::GrpcProject::Protos::Helpers::ServiceStatus>*(::grpc::ClientContext* context, const ::GrpcProject::Protos::Models::Product& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(ListProduct, ::grpc::Status(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::GrpcProject::Protos::Models::ListProductResponse* response));
  MOCK_METHOD3(AsyncListProductRaw, ::grpc::ClientAsyncResponseReaderInterface< ::GrpcProject::Protos::Models::ListProductResponse>*(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq));
  MOCK_METHOD3(PrepareAsyncListProductRaw, ::grpc::ClientAsyncResponseReaderInterface< ::GrpcProject::Protos::Models::ListProductResponse>*(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq));
};

} // namespace GrpcProject
} // namespace Protos
} // namespace Services

