// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Models/Invoice.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Models_2fInvoice_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Models_2fInvoice_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Models/Client.pb.h"
#include "Models/InvoiceDetails.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Models_2fInvoice_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Models_2fInvoice_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Models_2fInvoice_2eproto;
namespace GrpcProject {
namespace Protos {
namespace Models {
class Invoice;
struct InvoiceDefaultTypeInternal;
extern InvoiceDefaultTypeInternal _Invoice_default_instance_;
class InvoiceId;
struct InvoiceIdDefaultTypeInternal;
extern InvoiceIdDefaultTypeInternal _InvoiceId_default_instance_;
class ListInvoiceResponse;
struct ListInvoiceResponseDefaultTypeInternal;
extern ListInvoiceResponseDefaultTypeInternal _ListInvoiceResponse_default_instance_;
}  // namespace Models
}  // namespace Protos
}  // namespace GrpcProject
PROTOBUF_NAMESPACE_OPEN
template<> ::GrpcProject::Protos::Models::Invoice* Arena::CreateMaybeMessage<::GrpcProject::Protos::Models::Invoice>(Arena*);
template<> ::GrpcProject::Protos::Models::InvoiceId* Arena::CreateMaybeMessage<::GrpcProject::Protos::Models::InvoiceId>(Arena*);
template<> ::GrpcProject::Protos::Models::ListInvoiceResponse* Arena::CreateMaybeMessage<::GrpcProject::Protos::Models::ListInvoiceResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace GrpcProject {
namespace Protos {
namespace Models {

// ===================================================================

class Invoice final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:GrpcProject.Protos.Models.Invoice) */ {
 public:
  inline Invoice() : Invoice(nullptr) {}
  ~Invoice() override;
  explicit PROTOBUF_CONSTEXPR Invoice(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Invoice(const Invoice& from);
  Invoice(Invoice&& from) noexcept
    : Invoice() {
    *this = ::std::move(from);
  }

  inline Invoice& operator=(const Invoice& from) {
    CopyFrom(from);
    return *this;
  }
  inline Invoice& operator=(Invoice&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Invoice& default_instance() {
    return *internal_default_instance();
  }
  static inline const Invoice* internal_default_instance() {
    return reinterpret_cast<const Invoice*>(
               &_Invoice_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Invoice& a, Invoice& b) {
    a.Swap(&b);
  }
  inline void Swap(Invoice* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Invoice* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Invoice* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Invoice>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Invoice& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Invoice& from) {
    Invoice::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Invoice* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "GrpcProject.Protos.Models.Invoice";
  }
  protected:
  explicit Invoice(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 2,
    kAddressFieldNumber = 3,
    kInvoiceDetailsFieldNumber = 4,
    kIdFieldNumber = 1,
    kClientIdFieldNumber = 5,
  };
  // string name = 2;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string address = 3;
  void clear_address();
  const std::string& address() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_address(ArgT0&& arg0, ArgT... args);
  std::string* mutable_address();
  PROTOBUF_NODISCARD std::string* release_address();
  void set_allocated_address(std::string* address);
  private:
  const std::string& _internal_address() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_address(const std::string& value);
  std::string* _internal_mutable_address();
  public:

  // .GrpcProject.Protos.Models.InvoiceDetails invoice_details = 4;
  bool has_invoice_details() const;
  private:
  bool _internal_has_invoice_details() const;
  public:
  void clear_invoice_details();
  const ::GrpcProject::Protos::Models::InvoiceDetails& invoice_details() const;
  PROTOBUF_NODISCARD ::GrpcProject::Protos::Models::InvoiceDetails* release_invoice_details();
  ::GrpcProject::Protos::Models::InvoiceDetails* mutable_invoice_details();
  void set_allocated_invoice_details(::GrpcProject::Protos::Models::InvoiceDetails* invoice_details);
  private:
  const ::GrpcProject::Protos::Models::InvoiceDetails& _internal_invoice_details() const;
  ::GrpcProject::Protos::Models::InvoiceDetails* _internal_mutable_invoice_details();
  public:
  void unsafe_arena_set_allocated_invoice_details(
      ::GrpcProject::Protos::Models::InvoiceDetails* invoice_details);
  ::GrpcProject::Protos::Models::InvoiceDetails* unsafe_arena_release_invoice_details();

  // uint64 id = 1;
  void clear_id();
  uint64_t id() const;
  void set_id(uint64_t value);
  private:
  uint64_t _internal_id() const;
  void _internal_set_id(uint64_t value);
  public:

  // uint64 client_id = 5;
  void clear_client_id();
  uint64_t client_id() const;
  void set_client_id(uint64_t value);
  private:
  uint64_t _internal_client_id() const;
  void _internal_set_client_id(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:GrpcProject.Protos.Models.Invoice)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr address_;
    ::GrpcProject::Protos::Models::InvoiceDetails* invoice_details_;
    uint64_t id_;
    uint64_t client_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Models_2fInvoice_2eproto;
};
// -------------------------------------------------------------------

class InvoiceId final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:GrpcProject.Protos.Models.InvoiceId) */ {
 public:
  inline InvoiceId() : InvoiceId(nullptr) {}
  ~InvoiceId() override;
  explicit PROTOBUF_CONSTEXPR InvoiceId(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  InvoiceId(const InvoiceId& from);
  InvoiceId(InvoiceId&& from) noexcept
    : InvoiceId() {
    *this = ::std::move(from);
  }

  inline InvoiceId& operator=(const InvoiceId& from) {
    CopyFrom(from);
    return *this;
  }
  inline InvoiceId& operator=(InvoiceId&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const InvoiceId& default_instance() {
    return *internal_default_instance();
  }
  static inline const InvoiceId* internal_default_instance() {
    return reinterpret_cast<const InvoiceId*>(
               &_InvoiceId_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(InvoiceId& a, InvoiceId& b) {
    a.Swap(&b);
  }
  inline void Swap(InvoiceId* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InvoiceId* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  InvoiceId* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<InvoiceId>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const InvoiceId& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const InvoiceId& from) {
    InvoiceId::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InvoiceId* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "GrpcProject.Protos.Models.InvoiceId";
  }
  protected:
  explicit InvoiceId(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 1,
  };
  // uint64 id = 1;
  void clear_id();
  uint64_t id() const;
  void set_id(uint64_t value);
  private:
  uint64_t _internal_id() const;
  void _internal_set_id(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:GrpcProject.Protos.Models.InvoiceId)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Models_2fInvoice_2eproto;
};
// -------------------------------------------------------------------

class ListInvoiceResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:GrpcProject.Protos.Models.ListInvoiceResponse) */ {
 public:
  inline ListInvoiceResponse() : ListInvoiceResponse(nullptr) {}
  ~ListInvoiceResponse() override;
  explicit PROTOBUF_CONSTEXPR ListInvoiceResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ListInvoiceResponse(const ListInvoiceResponse& from);
  ListInvoiceResponse(ListInvoiceResponse&& from) noexcept
    : ListInvoiceResponse() {
    *this = ::std::move(from);
  }

  inline ListInvoiceResponse& operator=(const ListInvoiceResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ListInvoiceResponse& operator=(ListInvoiceResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ListInvoiceResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const ListInvoiceResponse* internal_default_instance() {
    return reinterpret_cast<const ListInvoiceResponse*>(
               &_ListInvoiceResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ListInvoiceResponse& a, ListInvoiceResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(ListInvoiceResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ListInvoiceResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ListInvoiceResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ListInvoiceResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ListInvoiceResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ListInvoiceResponse& from) {
    ListInvoiceResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ListInvoiceResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "GrpcProject.Protos.Models.ListInvoiceResponse";
  }
  protected:
  explicit ListInvoiceResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kInvoiceFieldNumber = 1,
  };
  // repeated .GrpcProject.Protos.Models.Invoice invoice = 1;
  int invoice_size() const;
  private:
  int _internal_invoice_size() const;
  public:
  void clear_invoice();
  ::GrpcProject::Protos::Models::Invoice* mutable_invoice(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::GrpcProject::Protos::Models::Invoice >*
      mutable_invoice();
  private:
  const ::GrpcProject::Protos::Models::Invoice& _internal_invoice(int index) const;
  ::GrpcProject::Protos::Models::Invoice* _internal_add_invoice();
  public:
  const ::GrpcProject::Protos::Models::Invoice& invoice(int index) const;
  ::GrpcProject::Protos::Models::Invoice* add_invoice();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::GrpcProject::Protos::Models::Invoice >&
      invoice() const;

  // @@protoc_insertion_point(class_scope:GrpcProject.Protos.Models.ListInvoiceResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::GrpcProject::Protos::Models::Invoice > invoice_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Models_2fInvoice_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Invoice

// uint64 id = 1;
inline void Invoice::clear_id() {
  _impl_.id_ = uint64_t{0u};
}
inline uint64_t Invoice::_internal_id() const {
  return _impl_.id_;
}
inline uint64_t Invoice::id() const {
  // @@protoc_insertion_point(field_get:GrpcProject.Protos.Models.Invoice.id)
  return _internal_id();
}
inline void Invoice::_internal_set_id(uint64_t value) {
  
  _impl_.id_ = value;
}
inline void Invoice::set_id(uint64_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:GrpcProject.Protos.Models.Invoice.id)
}

// string name = 2;
inline void Invoice::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& Invoice::name() const {
  // @@protoc_insertion_point(field_get:GrpcProject.Protos.Models.Invoice.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Invoice::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:GrpcProject.Protos.Models.Invoice.name)
}
inline std::string* Invoice::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:GrpcProject.Protos.Models.Invoice.name)
  return _s;
}
inline const std::string& Invoice::_internal_name() const {
  return _impl_.name_.Get();
}
inline void Invoice::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* Invoice::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* Invoice::release_name() {
  // @@protoc_insertion_point(field_release:GrpcProject.Protos.Models.Invoice.name)
  return _impl_.name_.Release();
}
inline void Invoice::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:GrpcProject.Protos.Models.Invoice.name)
}

// string address = 3;
inline void Invoice::clear_address() {
  _impl_.address_.ClearToEmpty();
}
inline const std::string& Invoice::address() const {
  // @@protoc_insertion_point(field_get:GrpcProject.Protos.Models.Invoice.address)
  return _internal_address();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Invoice::set_address(ArgT0&& arg0, ArgT... args) {
 
 _impl_.address_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:GrpcProject.Protos.Models.Invoice.address)
}
inline std::string* Invoice::mutable_address() {
  std::string* _s = _internal_mutable_address();
  // @@protoc_insertion_point(field_mutable:GrpcProject.Protos.Models.Invoice.address)
  return _s;
}
inline const std::string& Invoice::_internal_address() const {
  return _impl_.address_.Get();
}
inline void Invoice::_internal_set_address(const std::string& value) {
  
  _impl_.address_.Set(value, GetArenaForAllocation());
}
inline std::string* Invoice::_internal_mutable_address() {
  
  return _impl_.address_.Mutable(GetArenaForAllocation());
}
inline std::string* Invoice::release_address() {
  // @@protoc_insertion_point(field_release:GrpcProject.Protos.Models.Invoice.address)
  return _impl_.address_.Release();
}
inline void Invoice::set_allocated_address(std::string* address) {
  if (address != nullptr) {
    
  } else {
    
  }
  _impl_.address_.SetAllocated(address, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.address_.IsDefault()) {
    _impl_.address_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:GrpcProject.Protos.Models.Invoice.address)
}

// .GrpcProject.Protos.Models.InvoiceDetails invoice_details = 4;
inline bool Invoice::_internal_has_invoice_details() const {
  return this != internal_default_instance() && _impl_.invoice_details_ != nullptr;
}
inline bool Invoice::has_invoice_details() const {
  return _internal_has_invoice_details();
}
inline const ::GrpcProject::Protos::Models::InvoiceDetails& Invoice::_internal_invoice_details() const {
  const ::GrpcProject::Protos::Models::InvoiceDetails* p = _impl_.invoice_details_;
  return p != nullptr ? *p : reinterpret_cast<const ::GrpcProject::Protos::Models::InvoiceDetails&>(
      ::GrpcProject::Protos::Models::_InvoiceDetails_default_instance_);
}
inline const ::GrpcProject::Protos::Models::InvoiceDetails& Invoice::invoice_details() const {
  // @@protoc_insertion_point(field_get:GrpcProject.Protos.Models.Invoice.invoice_details)
  return _internal_invoice_details();
}
inline void Invoice::unsafe_arena_set_allocated_invoice_details(
    ::GrpcProject::Protos::Models::InvoiceDetails* invoice_details) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.invoice_details_);
  }
  _impl_.invoice_details_ = invoice_details;
  if (invoice_details) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:GrpcProject.Protos.Models.Invoice.invoice_details)
}
inline ::GrpcProject::Protos::Models::InvoiceDetails* Invoice::release_invoice_details() {
  
  ::GrpcProject::Protos::Models::InvoiceDetails* temp = _impl_.invoice_details_;
  _impl_.invoice_details_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::GrpcProject::Protos::Models::InvoiceDetails* Invoice::unsafe_arena_release_invoice_details() {
  // @@protoc_insertion_point(field_release:GrpcProject.Protos.Models.Invoice.invoice_details)
  
  ::GrpcProject::Protos::Models::InvoiceDetails* temp = _impl_.invoice_details_;
  _impl_.invoice_details_ = nullptr;
  return temp;
}
inline ::GrpcProject::Protos::Models::InvoiceDetails* Invoice::_internal_mutable_invoice_details() {
  
  if (_impl_.invoice_details_ == nullptr) {
    auto* p = CreateMaybeMessage<::GrpcProject::Protos::Models::InvoiceDetails>(GetArenaForAllocation());
    _impl_.invoice_details_ = p;
  }
  return _impl_.invoice_details_;
}
inline ::GrpcProject::Protos::Models::InvoiceDetails* Invoice::mutable_invoice_details() {
  ::GrpcProject::Protos::Models::InvoiceDetails* _msg = _internal_mutable_invoice_details();
  // @@protoc_insertion_point(field_mutable:GrpcProject.Protos.Models.Invoice.invoice_details)
  return _msg;
}
inline void Invoice::set_allocated_invoice_details(::GrpcProject::Protos::Models::InvoiceDetails* invoice_details) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.invoice_details_);
  }
  if (invoice_details) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(invoice_details));
    if (message_arena != submessage_arena) {
      invoice_details = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, invoice_details, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.invoice_details_ = invoice_details;
  // @@protoc_insertion_point(field_set_allocated:GrpcProject.Protos.Models.Invoice.invoice_details)
}

// uint64 client_id = 5;
inline void Invoice::clear_client_id() {
  _impl_.client_id_ = uint64_t{0u};
}
inline uint64_t Invoice::_internal_client_id() const {
  return _impl_.client_id_;
}
inline uint64_t Invoice::client_id() const {
  // @@protoc_insertion_point(field_get:GrpcProject.Protos.Models.Invoice.client_id)
  return _internal_client_id();
}
inline void Invoice::_internal_set_client_id(uint64_t value) {
  
  _impl_.client_id_ = value;
}
inline void Invoice::set_client_id(uint64_t value) {
  _internal_set_client_id(value);
  // @@protoc_insertion_point(field_set:GrpcProject.Protos.Models.Invoice.client_id)
}

// -------------------------------------------------------------------

// InvoiceId

// uint64 id = 1;
inline void InvoiceId::clear_id() {
  _impl_.id_ = uint64_t{0u};
}
inline uint64_t InvoiceId::_internal_id() const {
  return _impl_.id_;
}
inline uint64_t InvoiceId::id() const {
  // @@protoc_insertion_point(field_get:GrpcProject.Protos.Models.InvoiceId.id)
  return _internal_id();
}
inline void InvoiceId::_internal_set_id(uint64_t value) {
  
  _impl_.id_ = value;
}
inline void InvoiceId::set_id(uint64_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:GrpcProject.Protos.Models.InvoiceId.id)
}

// -------------------------------------------------------------------

// ListInvoiceResponse

// repeated .GrpcProject.Protos.Models.Invoice invoice = 1;
inline int ListInvoiceResponse::_internal_invoice_size() const {
  return _impl_.invoice_.size();
}
inline int ListInvoiceResponse::invoice_size() const {
  return _internal_invoice_size();
}
inline void ListInvoiceResponse::clear_invoice() {
  _impl_.invoice_.Clear();
}
inline ::GrpcProject::Protos::Models::Invoice* ListInvoiceResponse::mutable_invoice(int index) {
  // @@protoc_insertion_point(field_mutable:GrpcProject.Protos.Models.ListInvoiceResponse.invoice)
  return _impl_.invoice_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::GrpcProject::Protos::Models::Invoice >*
ListInvoiceResponse::mutable_invoice() {
  // @@protoc_insertion_point(field_mutable_list:GrpcProject.Protos.Models.ListInvoiceResponse.invoice)
  return &_impl_.invoice_;
}
inline const ::GrpcProject::Protos::Models::Invoice& ListInvoiceResponse::_internal_invoice(int index) const {
  return _impl_.invoice_.Get(index);
}
inline const ::GrpcProject::Protos::Models::Invoice& ListInvoiceResponse::invoice(int index) const {
  // @@protoc_insertion_point(field_get:GrpcProject.Protos.Models.ListInvoiceResponse.invoice)
  return _internal_invoice(index);
}
inline ::GrpcProject::Protos::Models::Invoice* ListInvoiceResponse::_internal_add_invoice() {
  return _impl_.invoice_.Add();
}
inline ::GrpcProject::Protos::Models::Invoice* ListInvoiceResponse::add_invoice() {
  ::GrpcProject::Protos::Models::Invoice* _add = _internal_add_invoice();
  // @@protoc_insertion_point(field_add:GrpcProject.Protos.Models.ListInvoiceResponse.invoice)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::GrpcProject::Protos::Models::Invoice >&
ListInvoiceResponse::invoice() const {
  // @@protoc_insertion_point(field_list:GrpcProject.Protos.Models.ListInvoiceResponse.invoice)
  return _impl_.invoice_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Models
}  // namespace Protos
}  // namespace GrpcProject

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Models_2fInvoice_2eproto
