// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Models/Invoice.proto

#include "Models/Invoice.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace GrpcProject {
namespace Protos {
namespace Models {
PROTOBUF_CONSTEXPR Invoice::Invoice(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.address_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.invoice_details_)*/nullptr
  , /*decltype(_impl_.id_)*/uint64_t{0u}
  , /*decltype(_impl_.client_id_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct InvoiceDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InvoiceDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~InvoiceDefaultTypeInternal() {}
  union {
    Invoice _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InvoiceDefaultTypeInternal _Invoice_default_instance_;
PROTOBUF_CONSTEXPR InvoiceId::InvoiceId(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.id_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct InvoiceIdDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InvoiceIdDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~InvoiceIdDefaultTypeInternal() {}
  union {
    InvoiceId _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InvoiceIdDefaultTypeInternal _InvoiceId_default_instance_;
PROTOBUF_CONSTEXPR ListInvoiceResponse::ListInvoiceResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.invoice_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ListInvoiceResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ListInvoiceResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ListInvoiceResponseDefaultTypeInternal() {}
  union {
    ListInvoiceResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ListInvoiceResponseDefaultTypeInternal _ListInvoiceResponse_default_instance_;
}  // namespace Models
}  // namespace Protos
}  // namespace GrpcProject
static ::_pb::Metadata file_level_metadata_Models_2fInvoice_2eproto[3];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_Models_2fInvoice_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_Models_2fInvoice_2eproto = nullptr;

const uint32_t TableStruct_Models_2fInvoice_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::GrpcProject::Protos::Models::Invoice, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::GrpcProject::Protos::Models::Invoice, _impl_.id_),
  PROTOBUF_FIELD_OFFSET(::GrpcProject::Protos::Models::Invoice, _impl_.name_),
  PROTOBUF_FIELD_OFFSET(::GrpcProject::Protos::Models::Invoice, _impl_.address_),
  PROTOBUF_FIELD_OFFSET(::GrpcProject::Protos::Models::Invoice, _impl_.invoice_details_),
  PROTOBUF_FIELD_OFFSET(::GrpcProject::Protos::Models::Invoice, _impl_.client_id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::GrpcProject::Protos::Models::InvoiceId, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::GrpcProject::Protos::Models::InvoiceId, _impl_.id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::GrpcProject::Protos::Models::ListInvoiceResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::GrpcProject::Protos::Models::ListInvoiceResponse, _impl_.invoice_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::GrpcProject::Protos::Models::Invoice)},
  { 11, -1, -1, sizeof(::GrpcProject::Protos::Models::InvoiceId)},
  { 18, -1, -1, sizeof(::GrpcProject::Protos::Models::ListInvoiceResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::GrpcProject::Protos::Models::_Invoice_default_instance_._instance,
  &::GrpcProject::Protos::Models::_InvoiceId_default_instance_._instance,
  &::GrpcProject::Protos::Models::_ListInvoiceResponse_default_instance_._instance,
};

const char descriptor_table_protodef_Models_2fInvoice_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\024Models/Invoice.proto\022\031GrpcProject.Prot"
  "os.Models\032\023Models/Client.proto\032\033Models/I"
  "nvoiceDetails.proto\"\213\001\n\007Invoice\022\n\n\002id\030\001 "
  "\001(\004\022\014\n\004name\030\002 \001(\t\022\017\n\007address\030\003 \001(\t\022B\n\017in"
  "voice_details\030\004 \001(\0132).GrpcProject.Protos"
  ".Models.InvoiceDetails\022\021\n\tclient_id\030\005 \001("
  "\004\"\027\n\tInvoiceId\022\n\n\002id\030\001 \001(\004\"J\n\023ListInvoic"
  "eResponse\0223\n\007invoice\030\001 \003(\0132\".GrpcProject"
  ".Protos.Models.Invoiceb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_Models_2fInvoice_2eproto_deps[2] = {
  &::descriptor_table_Models_2fClient_2eproto,
  &::descriptor_table_Models_2fInvoiceDetails_2eproto,
};
static ::_pbi::once_flag descriptor_table_Models_2fInvoice_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Models_2fInvoice_2eproto = {
    false, false, 350, descriptor_table_protodef_Models_2fInvoice_2eproto,
    "Models/Invoice.proto",
    &descriptor_table_Models_2fInvoice_2eproto_once, descriptor_table_Models_2fInvoice_2eproto_deps, 2, 3,
    schemas, file_default_instances, TableStruct_Models_2fInvoice_2eproto::offsets,
    file_level_metadata_Models_2fInvoice_2eproto, file_level_enum_descriptors_Models_2fInvoice_2eproto,
    file_level_service_descriptors_Models_2fInvoice_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Models_2fInvoice_2eproto_getter() {
  return &descriptor_table_Models_2fInvoice_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Models_2fInvoice_2eproto(&descriptor_table_Models_2fInvoice_2eproto);
namespace GrpcProject {
namespace Protos {
namespace Models {

// ===================================================================

class Invoice::_Internal {
 public:
  static const ::GrpcProject::Protos::Models::InvoiceDetails& invoice_details(const Invoice* msg);
};

const ::GrpcProject::Protos::Models::InvoiceDetails&
Invoice::_Internal::invoice_details(const Invoice* msg) {
  return *msg->_impl_.invoice_details_;
}
void Invoice::clear_invoice_details() {
  if (GetArenaForAllocation() == nullptr && _impl_.invoice_details_ != nullptr) {
    delete _impl_.invoice_details_;
  }
  _impl_.invoice_details_ = nullptr;
}
Invoice::Invoice(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:GrpcProject.Protos.Models.Invoice)
}
Invoice::Invoice(const Invoice& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Invoice* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.name_){}
    , decltype(_impl_.address_){}
    , decltype(_impl_.invoice_details_){nullptr}
    , decltype(_impl_.id_){}
    , decltype(_impl_.client_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_name().empty()) {
    _this->_impl_.name_.Set(from._internal_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.address_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.address_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_address().empty()) {
    _this->_impl_.address_.Set(from._internal_address(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_invoice_details()) {
    _this->_impl_.invoice_details_ = new ::GrpcProject::Protos::Models::InvoiceDetails(*from._impl_.invoice_details_);
  }
  ::memcpy(&_impl_.id_, &from._impl_.id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.client_id_) -
    reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.client_id_));
  // @@protoc_insertion_point(copy_constructor:GrpcProject.Protos.Models.Invoice)
}

inline void Invoice::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.name_){}
    , decltype(_impl_.address_){}
    , decltype(_impl_.invoice_details_){nullptr}
    , decltype(_impl_.id_){uint64_t{0u}}
    , decltype(_impl_.client_id_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.address_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.address_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Invoice::~Invoice() {
  // @@protoc_insertion_point(destructor:GrpcProject.Protos.Models.Invoice)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Invoice::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.name_.Destroy();
  _impl_.address_.Destroy();
  if (this != internal_default_instance()) delete _impl_.invoice_details_;
}

void Invoice::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Invoice::Clear() {
// @@protoc_insertion_point(message_clear_start:GrpcProject.Protos.Models.Invoice)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  _impl_.address_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.invoice_details_ != nullptr) {
    delete _impl_.invoice_details_;
  }
  _impl_.invoice_details_ = nullptr;
  ::memset(&_impl_.id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.client_id_) -
      reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.client_id_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Invoice::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string name = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "GrpcProject.Protos.Models.Invoice.name"));
        } else
          goto handle_unusual;
        continue;
      // string address = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_address();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "GrpcProject.Protos.Models.Invoice.address"));
        } else
          goto handle_unusual;
        continue;
      // .GrpcProject.Protos.Models.InvoiceDetails invoice_details = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_invoice_details(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 client_id = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.client_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Invoice::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:GrpcProject.Protos.Models.Invoice)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 id = 1;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_id(), target);
  }

  // string name = 2;
  if (!this->_internal_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "GrpcProject.Protos.Models.Invoice.name");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_name(), target);
  }

  // string address = 3;
  if (!this->_internal_address().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_address().data(), static_cast<int>(this->_internal_address().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "GrpcProject.Protos.Models.Invoice.address");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_address(), target);
  }

  // .GrpcProject.Protos.Models.InvoiceDetails invoice_details = 4;
  if (this->_internal_has_invoice_details()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, _Internal::invoice_details(this),
        _Internal::invoice_details(this).GetCachedSize(), target, stream);
  }

  // uint64 client_id = 5;
  if (this->_internal_client_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(5, this->_internal_client_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GrpcProject.Protos.Models.Invoice)
  return target;
}

size_t Invoice::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GrpcProject.Protos.Models.Invoice)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 2;
  if (!this->_internal_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // string address = 3;
  if (!this->_internal_address().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_address());
  }

  // .GrpcProject.Protos.Models.InvoiceDetails invoice_details = 4;
  if (this->_internal_has_invoice_details()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.invoice_details_);
  }

  // uint64 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_id());
  }

  // uint64 client_id = 5;
  if (this->_internal_client_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_client_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Invoice::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Invoice::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Invoice::GetClassData() const { return &_class_data_; }


void Invoice::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Invoice*>(&to_msg);
  auto& from = static_cast<const Invoice&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:GrpcProject.Protos.Models.Invoice)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (!from._internal_address().empty()) {
    _this->_internal_set_address(from._internal_address());
  }
  if (from._internal_has_invoice_details()) {
    _this->_internal_mutable_invoice_details()->::GrpcProject::Protos::Models::InvoiceDetails::MergeFrom(
        from._internal_invoice_details());
  }
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  if (from._internal_client_id() != 0) {
    _this->_internal_set_client_id(from._internal_client_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Invoice::CopyFrom(const Invoice& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GrpcProject.Protos.Models.Invoice)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Invoice::IsInitialized() const {
  return true;
}

void Invoice::InternalSwap(Invoice* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.name_, lhs_arena,
      &other->_impl_.name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.address_, lhs_arena,
      &other->_impl_.address_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Invoice, _impl_.client_id_)
      + sizeof(Invoice::_impl_.client_id_)
      - PROTOBUF_FIELD_OFFSET(Invoice, _impl_.invoice_details_)>(
          reinterpret_cast<char*>(&_impl_.invoice_details_),
          reinterpret_cast<char*>(&other->_impl_.invoice_details_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Invoice::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Models_2fInvoice_2eproto_getter, &descriptor_table_Models_2fInvoice_2eproto_once,
      file_level_metadata_Models_2fInvoice_2eproto[0]);
}

// ===================================================================

class InvoiceId::_Internal {
 public:
};

InvoiceId::InvoiceId(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:GrpcProject.Protos.Models.InvoiceId)
}
InvoiceId::InvoiceId(const InvoiceId& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  InvoiceId* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.id_ = from._impl_.id_;
  // @@protoc_insertion_point(copy_constructor:GrpcProject.Protos.Models.InvoiceId)
}

inline void InvoiceId::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.id_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

InvoiceId::~InvoiceId() {
  // @@protoc_insertion_point(destructor:GrpcProject.Protos.Models.InvoiceId)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void InvoiceId::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void InvoiceId::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void InvoiceId::Clear() {
// @@protoc_insertion_point(message_clear_start:GrpcProject.Protos.Models.InvoiceId)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.id_ = uint64_t{0u};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* InvoiceId::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* InvoiceId::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:GrpcProject.Protos.Models.InvoiceId)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 id = 1;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GrpcProject.Protos.Models.InvoiceId)
  return target;
}

size_t InvoiceId::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GrpcProject.Protos.Models.InvoiceId)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData InvoiceId::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    InvoiceId::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*InvoiceId::GetClassData() const { return &_class_data_; }


void InvoiceId::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<InvoiceId*>(&to_msg);
  auto& from = static_cast<const InvoiceId&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:GrpcProject.Protos.Models.InvoiceId)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void InvoiceId::CopyFrom(const InvoiceId& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GrpcProject.Protos.Models.InvoiceId)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool InvoiceId::IsInitialized() const {
  return true;
}

void InvoiceId::InternalSwap(InvoiceId* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.id_, other->_impl_.id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata InvoiceId::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Models_2fInvoice_2eproto_getter, &descriptor_table_Models_2fInvoice_2eproto_once,
      file_level_metadata_Models_2fInvoice_2eproto[1]);
}

// ===================================================================

class ListInvoiceResponse::_Internal {
 public:
};

ListInvoiceResponse::ListInvoiceResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:GrpcProject.Protos.Models.ListInvoiceResponse)
}
ListInvoiceResponse::ListInvoiceResponse(const ListInvoiceResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ListInvoiceResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.invoice_){from._impl_.invoice_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:GrpcProject.Protos.Models.ListInvoiceResponse)
}

inline void ListInvoiceResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.invoice_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ListInvoiceResponse::~ListInvoiceResponse() {
  // @@protoc_insertion_point(destructor:GrpcProject.Protos.Models.ListInvoiceResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ListInvoiceResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.invoice_.~RepeatedPtrField();
}

void ListInvoiceResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ListInvoiceResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:GrpcProject.Protos.Models.ListInvoiceResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.invoice_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ListInvoiceResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .GrpcProject.Protos.Models.Invoice invoice = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_invoice(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ListInvoiceResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:GrpcProject.Protos.Models.ListInvoiceResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .GrpcProject.Protos.Models.Invoice invoice = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_invoice_size()); i < n; i++) {
    const auto& repfield = this->_internal_invoice(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:GrpcProject.Protos.Models.ListInvoiceResponse)
  return target;
}

size_t ListInvoiceResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:GrpcProject.Protos.Models.ListInvoiceResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .GrpcProject.Protos.Models.Invoice invoice = 1;
  total_size += 1UL * this->_internal_invoice_size();
  for (const auto& msg : this->_impl_.invoice_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ListInvoiceResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ListInvoiceResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ListInvoiceResponse::GetClassData() const { return &_class_data_; }


void ListInvoiceResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ListInvoiceResponse*>(&to_msg);
  auto& from = static_cast<const ListInvoiceResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:GrpcProject.Protos.Models.ListInvoiceResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.invoice_.MergeFrom(from._impl_.invoice_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ListInvoiceResponse::CopyFrom(const ListInvoiceResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GrpcProject.Protos.Models.ListInvoiceResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ListInvoiceResponse::IsInitialized() const {
  return true;
}

void ListInvoiceResponse::InternalSwap(ListInvoiceResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.invoice_.InternalSwap(&other->_impl_.invoice_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ListInvoiceResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Models_2fInvoice_2eproto_getter, &descriptor_table_Models_2fInvoice_2eproto_once,
      file_level_metadata_Models_2fInvoice_2eproto[2]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Models
}  // namespace Protos
}  // namespace GrpcProject
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::GrpcProject::Protos::Models::Invoice*
Arena::CreateMaybeMessage< ::GrpcProject::Protos::Models::Invoice >(Arena* arena) {
  return Arena::CreateMessageInternal< ::GrpcProject::Protos::Models::Invoice >(arena);
}
template<> PROTOBUF_NOINLINE ::GrpcProject::Protos::Models::InvoiceId*
Arena::CreateMaybeMessage< ::GrpcProject::Protos::Models::InvoiceId >(Arena* arena) {
  return Arena::CreateMessageInternal< ::GrpcProject::Protos::Models::InvoiceId >(arena);
}
template<> PROTOBUF_NOINLINE ::GrpcProject::Protos::Models::ListInvoiceResponse*
Arena::CreateMaybeMessage< ::GrpcProject::Protos::Models::ListInvoiceResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::GrpcProject::Protos::Models::ListInvoiceResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
