// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Helpers/ServiceStatus.proto

#include "Helpers/ServiceStatus.pb.h"
#include "Helpers/ServiceStatus.grpc.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/sync_stream.h>
#include <gmock/gmock.h>
namespace GrpcProject {
namespace Protos {
namespace Helpers {

} // namespace GrpcProject
} // namespace Protos
} // namespace Helpers

